name: modish_fashion_ecommerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_offline: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_generative_ai: ^0.4.6
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mime_type: ^1.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

flutter_native_splash:
  color: "#F8F9FA" # Color of the background of the splash screen
  image: assets/master/splash_screen.png # image path
  android_12:
    image: assets/master/splash_screen.png # image path
    color: "#F8F9FA" # Color of the background of the splash screen

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/master/icon.png" # Logo image path
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/master/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
